ExchangeApp/Models/FacultiesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExchangeApp.Models
{
    public class FacultiesViewModel
    {
        public IEnumerable<Faculty> StudentsPlaces { get; set; }

        public IEnumerable<Faculty> TeacherPlaces { get; set; }

    }
}

ExchangeApp/Models/Faculty.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ExchangeApp.Models
{
    public class Faculty : BaseObject
    {
        [Required(ErrorMessage = "Please enter college/university name")]
        [Display(Name = "College/university name")]
        [StringLength(50)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter program")]
        [Display(Name = "Program")]
        [StringLength(50)]
        public string Program { get; set; }

        [Required(ErrorMessage = "Please enter email")]
        [Display(Name = "Email")]
        [StringLength(50)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter description")]
        [Display(Name = "Description")]
        [StringLength(4000)]
        public string Description { get; set; }

        [Required(ErrorMessage = "Please enter agreement number")]
        [Display(Name = "Agreement number")]
        [StringLength(20)]
        public string AgreementNumber { get; set; }

        [Required(ErrorMessage = "Please enter website")]
        [Display(Name = "Website")]
        [StringLength(50)]
        public string Website { get; set; }

        [Required(ErrorMessage = "Please choose country")]
        [Display(Name = "Country")]
        public int? CountryId { get; set; }

        [Display(Name = "Country")]
        [ForeignKey("CountryId")]
        public virtual NomCountry CountryObj { get; set; }

        [Required(ErrorMessage = "Please choose date of membership")]
        [Display(Name = "Date of Membership")]
        public DateTime? DateOfMatriculation { get; set; }

        [Required(ErrorMessage = "Please enter accreditation number")]
        [Display(Name = "Accreditation number")]
        public int AccreditationNumber { get; set; }

        [Required(ErrorMessage = "Please choose date of accreditation")]
        [Display(Name = "Date of Accreditation")]
        public DateTime? DateOfAccreditation { get; set; }

        [Display(Name = "Student places available for exchange")]
        public int? StudentPlacesAvailable { get; set; }

        [Display(Name = "Student application date")]
        public DateTime? StudentApplicationDate { get; set; }

        [Display(Name = "Student enrollment date")]
        public DateTime? StudentEnrollmentDate { get; set; }

        [Display(Name = "Faculty places available for exchange")]
        public int? FacultyPlacesAvailable { get; set; }

        [Display(Name = "Faculty application date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime? FacultyApplicationDate { get; set; }

        [Display(Name = "Faculty enrollment date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime? FacultyEnrollmentDate { get; set; }

        [Display(Name = "Student type of exchange")]
        public int? StudentTypeOfExchangeId { get; set; }

        [Display(Name = "Student type of exchange")]
        [ForeignKey("StudentTypeOfExchangeId")]
        public virtual NomTypeOfExchange StudentTypeOfExchangeObj { get; set; }

        [Display(Name = "Faculty type of exchange")]
        public int? FacultyTypeOfExchangeId { get; set; }

        [Display(Name = "Faculty type of exchange")]
        [ForeignKey("FacultyTypeOfExchangeId")]
        public virtual NomTypeOfExchange FacultyTypeOfExchangeObj { get; set; }

        [Display(Name = "Featured faculty")]
        public bool? IsFeatured { get; set; }

        [Display(Name = "Display")]
        public bool? Display { get; set; }

        [NotMapped]
        public int[] SelectedSubjectsIds { get; set; }

        public virtual ICollection<FacultyCourses> Courses { get; set; }

        public byte[] LogoImage { get; set; }

        [NotMapped]
        public string CoursesString { get; set; }

    }
}

ExchangeApp/Models/FacultyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ExchangeApp.Models
{
    public class FacultyViewModel
    {
        public int ID { get; set; }

        public string Name { get; set; }

        public string Program { get; set; }

        public string Email { get; set; }

        public string Description { get; set; }

        public string AgreementNumber { get; set; }

        public string Website { get; set; }

        public int? CountryId { get; set; }

        public virtual NomCountry CountryObj { get; set; }

        public DateTime? DateOfMatriculation { get; set; }

        public int AccreditationNumber { get; set; }

        public DateTime? DateOfAccreditation { get; set; }

        public int? StudentPlacesAvailable { get; set; }

        public DateTime? StudentApplicationDate { get; set; }

        public DateTime? StudentEnrollmentDate { get; set; }

        public int? FacultyPlacesAvailable { get; set; }

        public DateTime? FacultyApplicationDate { get; set; }

        public DateTime? FacultyEnrollmentDate { get; set; }

        public int? StudentTypeOfExchangeId { get; set; }

        public virtual NomTypeOfExchange StudentTypeOfExchangeObj { get; set; }

        public int? FacultyTypeOfExchangeId { get; set; }

        public virtual NomTypeOfExchange FacultyTypeOfExchangeObj { get; set; }

        public bool? IsFeatured { get; set; }

        public bool? Display { get; set; }

        public virtual ICollection<Subject> Subjects { get; set; }

        public byte[] LogoImage { get; set; }

        public FacultyViewModel(Faculty faculty)
        {
            this.ID = faculty.ID;
            this.Name = faculty.Name;
            this.Program = faculty.Program;
            this.Email = faculty.Email;
            this.Description = faculty.Description;
            this.AgreementNumber = faculty.AgreementNumber;
            this.Website = faculty.Website;
            this.CountryId = faculty.CountryId;
            this.CountryObj = faculty.CountryObj;
            this.DateOfAccreditation = faculty.DateOfAccreditation;
            this.DateOfMatriculation = faculty.DateOfMatriculation;
            this.AccreditationNumber = faculty.AccreditationNumber;
            this.StudentApplicationDate = faculty.StudentApplicationDate;
            this.StudentEnrollmentDate = faculty.StudentEnrollmentDate;
            this.StudentPlacesAvailable = faculty.StudentPlacesAvailable;
            this.StudentTypeOfExchangeId = faculty.StudentTypeOfExchangeId;
            this.StudentTypeOfExchangeObj = faculty.StudentTypeOfExchangeObj;
            this.FacultyApplicationDate = faculty.FacultyApplicationDate;
            this.FacultyEnrollmentDate = faculty.FacultyEnrollmentDate;
            this.FacultyPlacesAvailable = faculty.FacultyPlacesAvailable;
            this.FacultyTypeOfExchangeId = faculty.FacultyTypeOfExchangeId;
            this.FacultyTypeOfExchangeObj = faculty.FacultyTypeOfExchangeObj;
            this.IsFeatured = faculty.IsFeatured;
            this.Display = faculty.Display;

            this.LogoImage = faculty.LogoImage;
            
    }

        public FacultyViewModel()
        {

        }
    }
}

ExchangeApp/Controllers/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExchangeApp.Models;
using PagedList;

namespace ExchangeApp.Controllers
{
    public class FacultiesController : BaseAdminController
    {

        // GET: Faculties
        public ActionResult Index(int? page,int ? RegionId, int? currentRegion)
        {
            ViewBag.CurrentRegion = RegionId.HasValue ? RegionId : currentRegion;

            NomRegion initial = new NomRegion();
            initial.ID = -1;
            initial.Name = "All regions";
            List<Models.NomRegion> list = new List<Models.NomRegion>();
            list.Add(initial);
            list.AddRange(db.Regions);
            
            ViewBag.RegionId = new SelectList(list, "ID", "Name", ViewBag.CurrentRegion);

            if (!RegionId.HasValue)
            {
                RegionId = currentRegion;
            }

            var faculties = db.Faculties.Include(f => f.CountryObj).Include(f => f.FacultyTypeOfExchangeObj).Include(f => f.LastUpdatedByUser).Include(f => f.RegisteredByUser).Include(f => f.StudentTypeOfExchangeObj);

            if (RegionId.HasValue && RegionId != -1)
            {
                faculties = faculties.Where(f => f.CountryObj != null && f.CountryObj.RegionId == RegionId);
            }


            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(faculties.OrderBy(l => l.Name).ToPagedList(pageNumber, pageSize));
        }

        // GET: Faculties/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            return View(faculty);
        }

        // GET: Faculties/Create
        public ActionResult Create()
        {
            List<NomCountry> countriesList = db.Countries.OrderBy(x => x.Name).ToList();
            ViewBag.CountriesList = new SelectList(countriesList, "ID", "Name");

            List<NomTypeOfExchange> typesOfExchangesStudent = db.TypesOfExchange.Where(t => t.Student.HasValue && t.Student.Value).ToList();
            List<NomTypeOfExchange> typesOfExchangesFaculty = db.TypesOfExchange.Where(t => t.Faculty.HasValue && t.Faculty.Value).ToList();
            ViewBag.TypesOfExchangeStudent = new SelectList(typesOfExchangesStudent, "ID", "Name");
            ViewBag.TypesOfExchangeFaculty = new SelectList(typesOfExchangesFaculty, "ID", "Name");

            List<Subject> subjects = db.Subjects.ToList();
            ViewBag.Subjects = new MultiSelectList(subjects, "ID", "Name");

            ViewBag.LastUpdatedBy = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.RegisteredBy = new SelectList(db.Users, "Id", "FirstName");

            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Program,Email,Description,AgreementNumber,Website,CountryId,DateOfMatriculation,AccreditationNumber,DateOfAccreditation,StudentPlacesAvailable,StudentApplicationDate,StudentEnrollmentDate,FacultyPlacesAvailable,FacultyApplicationDate,FacultyEnrollmentDate,StudentTypeOfExchangeId,FacultyTypeOfExchangeId, IsFeatured, Display, SelectedSubjectsIds")] Faculty faculty, bool StudentSelected, bool FacultySelected, HttpPostedFileBase File)
        {

            if (db.Faculties.Any(x => x.Name.ToLower() == faculty.Name.ToLower()))
            {
                ModelState.AddModelError("Name", "College/university with that name already exists");
            }

            if (!StudentSelected && !FacultySelected)
            {
                ModelState.AddModelError("", "Please select type of exchange that you offer");
            }

            if (StudentSelected)
            {
                if (faculty.StudentTypeOfExchangeId == null)
                {
                    ModelState.AddModelError("StudentTypeOfExchangeId", "Please choose student type of exchange");
                }
                if (faculty.StudentPlacesAvailable == null || faculty.StudentPlacesAvailable == 0)
                {
                    ModelState.AddModelError("StudentPlacesAvailable", "Please enter student places available");
                }
                if (faculty.StudentApplicationDate == null)
                {
                    ModelState.AddModelError("StudentApplicationDate", "Please choose application date");
                }
                if (faculty.StudentEnrollmentDate == null)
                {
                    ModelState.AddModelError("StudentEnrollmentDate", "Please choose enrollment date");
                }
            }

            if (FacultySelected)
            {
                if (faculty.FacultyTypeOfExchangeId == null)
                {
                    ModelState.AddModelError("FacultyTypeOfExchangeId", "Please choose faculty type of exchange");
                }
                if (faculty.FacultyPlacesAvailable == null || faculty.FacultyPlacesAvailable == 0)
                {
                    ModelState.AddModelError("FacultyPlacesAvailable", "Please enter faculty places available");
                }
                if (faculty.FacultyApplicationDate == null)
                {
                    ModelState.AddModelError("FacultyApplicationDate", "Please choose application date");
                }
                if (faculty.FacultyEnrollmentDate == null)
                {
                    ModelState.AddModelError("FacultyEnrollmentDate", "Please choose enrollment date");
                }
                if (faculty.SelectedSubjectsIds == null || faculty.SelectedSubjectsIds.Count() == 0)
                {
                    ModelState.AddModelError("SelectedSubjectsIds", "Please choose at least one course");
                }
            }

            if (ModelState.IsValid)
            {
                if (File != null)
                {
                    if (IsValidImage(File))
                    {
                        byte[] image = new byte[File.ContentLength];
                        File.InputStream.Read(image, 0, image.Length);
                        faculty.LogoImage = image;
                    }
                    else
                    {
                        DisplayErrorMessage("Image format is not valid or image is bigger than 3MB!");
                        return RedirectToAction("Index");
                    }
                }

                if (faculty.SelectedSubjectsIds != null)
                {
                    for (var i = 0; i < faculty.SelectedSubjectsIds.Count(); i++)
                    {
                        FacultyCourses fc = new FacultyCourses();
                        fc.FacultyId = faculty.ID;
                        fc.FacultyObj = faculty;

                        var SubjectObj = db.Subjects.Find(faculty.SelectedSubjectsIds[i]);
                        fc.SubjectId = faculty.SelectedSubjectsIds[i];
                        fc.SubjectObj = SubjectObj;

                        db.FacultyCourses.Add(fc);
                    }
                }

                db.Faculties.Add(faculty);
                db.SaveChanges();
                DisplaySuccessMessage("Successfully added new faculty!");
                return RedirectToAction("Index");
            }

            List<NomCountry> countriesList = db.Countries.OrderBy(x => x.Name).ToList();
            ViewBag.CountriesList = new SelectList(countriesList, "ID", "Name");

            List<NomTypeOfExchange> typesOfExchangesStudent = db.TypesOfExchange.Where(t => t.Student.HasValue && t.Student.Value).ToList();
            List<NomTypeOfExchange> typesOfExchangesFaculty = db.TypesOfExchange.Where(t => t.Faculty.HasValue && t.Faculty.Value).ToList();
            ViewBag.TypesOfExchangeStudent = new SelectList(typesOfExchangesStudent, "ID", "Name");
            ViewBag.TypesOfExchangeFaculty = new SelectList(typesOfExchangesFaculty, "ID", "Name");

            List<Subject> subjects = db.Subjects.ToList();
            ViewBag.Subjects = new MultiSelectList(subjects, "ID", "Name");

            ViewBag.LastUpdatedBy = new SelectList(db.Users, "Id", "FirstName", faculty.LastUpdatedBy);
            ViewBag.RegisteredBy = new SelectList(db.Users, "Id", "FirstName", faculty.RegisteredBy);

            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Faculty faculty = db.Faculties.Find(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            List<NomTypeOfExchange> typesOfExchangesStudent = db.TypesOfExchange.Where(t=>t.Student.HasValue && t.Student.Value).ToList();
            List<NomTypeOfExchange> typesOfExchangesFaculty = db.TypesOfExchange.Where(t => t.Faculty.HasValue && t.Faculty.Value).ToList();
            List<Subject> subjects = db.Subjects.ToList();
            ViewBag.Subjects = new MultiSelectList(subjects, "ID", "Name");

     
            ViewBag.FacultyTypeOfExchangeId = new SelectList(typesOfExchangesFaculty, "ID", "Name", faculty.FacultyTypeOfExchangeId);
            ViewBag.StudentTypeOfExchangeId = new SelectList(typesOfExchangesStudent, "ID", "Name", faculty.StudentTypeOfExchangeId);

ExchangeApp/Views/Faculties/Details.cshtml
@model ExchangeApp.Models.Faculty

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="interior site">
        <div>
            <div>
                <a href="@Url.Action("Index", "Faculties")" title="Back" style="font-size: 25px;"><i class="icon ion-android-arrow-dropleft-circle"></i></a>
                <span class="fax-title">@Html.DisplayFor(model => model.Name)</span>
                <a href="@Url.Action("Edit", "Faculties", new { id = Model.ID })" class="fr"><button class="primary" type="submit">Edit</button></a>
            </div>
            <div class="tab-content mt-20">
                <table class="table">
                    <tbody>
                        <tr>
                            <td class="details" style="vertical-align: middle">Logo</td>
                            <td>
                                @if (Model.LogoImage != null)
                                {
                                    <img style="max-height: 100px" src="data:image;base64,@System.Convert.ToBase64String(Model.LogoImage)" />
                                }
                                else
                                {
                                    <img style="max-height: 100px" src="~/Content/images/No_Image_Available.jpg" />

                                }
                            </td>
                        </tr>
                        <tr>
                            <td class="details">Country/State</td>
                            <td>@Html.DisplayFor(model => model.CountryObj.Name)</td>
                        </tr>
                        <tr>
                            <td class="details">Program</td>
                            <td>@Html.DisplayFor(model => model.Program)</td>
                        </tr>
                        <tr>
                            <td class="details">@Html.DisplayNameFor(model => model.AgreementNumber)</td>
                            <td>@Html.DisplayFor(model => model.AgreementNumber)</td>
                        </tr>
                        <tr>
                            <td class="details">@Html.DisplayNameFor(model => model.Email)</td>
                            <td>@Html.DisplayFor(model => model.Email)</td>
                        </tr>
                        <tr>
                            <td class="details"> @Html.DisplayNameFor(model => model.Website)</td>
                            <td>@Html.DisplayFor(model => model.Website)</td>
                        </tr>
                        <tr>
                            <td class="details">@Html.DisplayNameFor(model => model.DateOfMatriculation)</td>
                            <td>@Html.DisplayFor(model => model.DateOfMatriculation)</td>
                        </tr>
                        <tr>
                            <td class="details">@Html.DisplayNameFor(model => model.AccreditationNumber)</td>
                            <td>@Html.DisplayFor(model => model.AccreditationNumber)</td>
                        </tr>
                        <tr>
                            <td class="details">@Html.DisplayNameFor(model => model.DateOfAccreditation)</td>
                            <td>@Html.DisplayFor(model => model.DateOfAccreditation)</td>
                        </tr>
                        <tr>
                            <td rowspan="5" class="details" style="vertical-align: middle">Student</td>
                        </tr>
                        <tr>
                            <td>Type of exchange: @Html.DisplayFor(model => model.StudentTypeOfExchangeObj.Name)</td>
                        </tr>
                        <tr>
                            <td>Places Available: @Html.DisplayFor(model => model.StudentPlacesAvailable)</td>
                        </tr>
                        <tr>
                            <td>Application Date: @Html.DisplayFor(model => model.StudentApplicationDate)</td>
                        </tr>
                        <tr>
                            <td></i>Enrollment Date: @Html.DisplayFor(model => model.StudentEnrollmentDate)</td>
                        </tr>

                        <tr>
                            <td rowspan="5" class="details" style="vertical-align: middle">Faculty</td>
                        </tr>
                        <tr>
                            <td>Type of exchange: @Html.DisplayFor(model => model.FacultyTypeOfExchangeObj.Name)</td>
                        </tr>
                        <tr>
                            <td>Places Available: @Html.DisplayFor(model => model.FacultyPlacesAvailable)</td>
                        </tr>
                        <tr>
                            <td>Application Date: @Html.DisplayFor(model => model.FacultyApplicationDate)</td>
                        </tr>
                        <tr>
                            <td>Enrollment Date: @Html.DisplayFor(model => model.FacultyEnrollmentDate)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

ExchangeApp/Views/Faculties/Index.cshtml
@model PagedList.IPagedList<ExchangeApp.Models.Faculty>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Colleges/Universities";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="interior site">
        <div>
            <a href="@Url.Action("Index", "Admin" )" title="Back" style="font-size: 25px;"><i class="icon ion-android-arrow-dropleft-circle"></i></a>
            <a href="@Url.Action("Create", "Faculties")"><button class="primary btn-create" type="submit">Add new</button></a>
        </div>

        @using (Html.BeginForm("Index", "Faculties"))
        {
        <div style="margin-bottom:50px;">
            <div class="select-style" style="display:inline-block; width:250px;">
                @Html.DropDownList("RegionId")
            </div>

            <button class="primary primary-applied" type="submit">Search</button>
        </div>
        <div class="table">
            <div class="row header">
                <div class="cell">
                    College/University
                </div>
                <div class="cell">
                    Program
                </div>
                <div class="cell">
                    Country/State
                </div>
                <div class="cell">
                    Actions
                </div>
            </div>

            @foreach (var item in Model)
            {
            <div class="row">
                <div class="cell">
                    @Html.DisplayFor(modelItem => item.Name)
                </div>
                <div class="cell">
                    @Html.DisplayFor(modelItem => item.Program)
                </div>
                <div class="cell">
                    @Html.DisplayFor(modelItem => item.CountryObj.Name)
                </div>
                <div class="cell-act">
                    <a href="@Url.Action("Edit", "Faculties", new { id = item.ID })" title="Edit"><i class="icon ion-ios-compose-outline"></i></a> |
                    <a href="@Url.Action("Details", "Faculties", new { id = item.ID })" title="Details"><i class="icon ion-ios-list-outline"></i></a> |
                    <a onclick="DeleteFaculty(@item.ID)" title="Delete"><i class="icon ion-ios-trash-outline"></i></a>
                </div>
            </div>

            }

            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-sm " role="document">
                    <div class="modal-content">
                        <div class="modal-header pd-5">
                            <h4 class="modal-title" id="myModalLabel">Confirmation dialog</h4>
                        </div>
                        <div class="modal-body pd-10">
                            Are you sure you want to delete the college/university along with all of his subjects?
                        </div>
                        <div class="modal-footer pd-0">
                            <div>
                                <div class="col-lg-6 col-md-10 mt-20">
                                    <button class="btn btn-default" data-dismiss="modal">Cancel</button>
                                </div>
                                <div class="col-lg-6 col-md-10 mt-20">
                                    <button class="btn btn-danger" type="submit" onclick="ConfirmDelete()">Delete</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="custom-pag" style="text-align:center;">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentRegion = ViewBag.CurrentRegion }))

        </div>
        }
        <input type="hidden" id="hiddenId" />
    </div>
    @section scripts {
        <script>
            var DeleteFaculty = function (facultyId) {
                $("#deleteModal").modal("show");
                $("#hiddenId").val(facultyId)
            }

            var ConfirmDelete = function () {
                var facultyId = $("#hiddenId").val();
                $.ajax({
                    type: "POST",
                    url: "/Faculties/DeleteFaculty",
                    data: { id: facultyId },
                    success: function (data) {
                        $("#deleteModal").modal("hide");
                        window.location.href = "/Faculties/Index"
                    }
                });
            }
        </script>
    }